objects/SlickSidebar__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Accordion_Arrow_Colour__c</fullName>
        <defaultValue>&quot;#009DDC&quot;</defaultValue>
        <inlineHelpText>HEX colour code for the accordion arrows</inlineHelpText>
        <label>Accordion Arrow Colour</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Row_Hover_Colour__c</fullName>
        <defaultValue>&quot;#E0F0FF&quot;</defaultValue>
        <inlineHelpText>HEX colour for mouse hover</inlineHelpText>
        <label>Row Hover Colour</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Show_Activity_History__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Show Activity History</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Customer_Summary__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Show Customer Summary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Generic_Related_List_1__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Show Generic Related List 1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Generic_Related_List_2__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Show Generic Related List 2</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Nearby_Locations__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Show Nearby Locations</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Related_Cases__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Show Related Cases</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Related_Opportunities__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Show Related Opportunities</label>
        <type>Checkbox</type>
    </fields>
    <label>SlickSidebar Configuration</label>
</CustomObject>

classes/SlickSidebarAbstractController.cls
// Copyright 2014, Kevin Akermanis - Sales Engineering, Salesforce.com Inc.
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
// - Redistributions of source code must retain the above copyright notice,
//   this list of conditions and the following disclaimer.
// - Redistributions in binary form must reproduce the above copyright notice,
//   this list of conditions and the following disclaimer in the documentation
//   and/or other materials provided with the distribution.
// - Neither the name of the salesforce.com nor the names of its contributors
//   may be used to endorse or promote products derived from this software
//   without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
// OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


/**
 *
 * Centralised class to abstract what the primary and focus tab types are for each of the implemented Console Widgets
 * Allows for more easily transportable console widgets without being tied to the Console tab/subtab configuration
 * All underlying console widgets will call the static Setter/Getters within this class to get the context they require for base objects
 *
 * Base FieldSets for Account / Contact / Case are:
 * AccountConsoleWrapper / ContactConsoleWrapper / CaseConsoleWrapper respectively
 *  
 **/
public abstract class SlickSidebarAbstractController {
  public Account currAccount {set;get;}
  public Contact currContact {set;get;}
  public Case currCase {set;get;}
  public ID currRecordId {set;get;}
  public String currRecordType {set;get;}
  public ID primaryTabRecordId {set;get;}
  public String primaryTabObjectType {set;get;}
  public SlickSidebar__c config {set;get;}

  //new
    public Lead currLead {get;set;}
    
	public SlickSidebarAbstractController() {
		init();
        loadWidget();
	}  
    
    public abstract void loadWidget();     
  
  public virtual void init() {
      
	System.debug('Inside SlickSidebarAbstractController.init()...');      
	currRecordId = ID.valueOf(ApexPages.currentPage().getParameters().get('Id'));           
	if (currRecordId != null) {
        primaryTabRecordId = currRecordId;
        primaryTabObjectType = String.valueOf(currRecordId.getSObjectType());
		currRecordType = String.valueOf(currRecordId.getSObjectType());
		System.debug('Inside SlickSidebarController with object type of: ' + currRecordType);        
    
        
        //TODO: Look at removing this once Slick becomes individual accordion components
        config = [SELECT Accordion_Arrow_Colour__c, Show_Customer_Summary__c, Show_Related_Cases__c, Show_Activity_History__c, Show_Nearby_Locations__c,
              Show_Related_Opportunities__c, Show_Generic_Related_List_1__c, Show_Generic_Related_List_2__c, Row_Hover_Colour__c
              FROM SlickSidebar__c LIMIT 1];   
            
          if (Account.getSObjectType() == currRecordId.getSObjectType()) {
            // Primary tab is an Account
            // Check if the current account it a person account or a normal account...
            // TODO: CANNOT IMPLEMENT THIS CHECK UNTIL PERSON ACCOUNTS HAVE BEEN ENABLED....
            // If it's a person account populate both the contact and account objects
            System.debug('SlickSidebarController - fetching records based on passed in Account ID');        
    
            if ( isPersonAccountRecord(currRecordId) ) {
              System.debug('Passed in Account Record is a person account');
              currAccount = getAccountRecord(currRecordId);
              currContact = getPersonAccountContactRecord(currRecordId);
              currCase = null;          
            } else {
              System.debug('Passed in Account Record is a regular account');
              currAccount = getAccountRecord(currRecordId);
              currContact = null;
              currCase = null;
            }
          } else if (Case.getSObjectType() == currRecordId.getSObjectType()) {
            // Primary Tab is a Case
            // Grab the Contact and Account from the case record
            System.debug('SlickSidebarController - fetching records based on passed in Case ID');
            currCase = getCaseRecord(currRecordId);
            currContact = getContactRecord(currCase.contactId);
            currAccount = getAccountRecord(currCase.accountId);
          } else if(Contact.getSObjectType() == currRecordId.getSObjectType()) {    
            // Primary Tab is a Contact
            // Grab the account infomration off the contact record
            System.debug('SlickSidebarController - fetching records based on passed in Contact ID');
            currContact = getContactRecord(currRecordId);
            currAccount = getAccountRecord(currContact.accountId);
            currCase = null;
          }
                
                //new
                else if(Lead.getSObjectType() == currRecordId.getSObjectType()) {    
            // Primary Tab is a Lead
            // Grab the account infomration off the contact record
            System.debug('SlickSidebarController - fetching records based on passed in Lead ID');
            currLead = getLeadRecord(currRecordId);
            currAccount = null;
            currCase = null; 
		} else {
            System.debug('I dont know what type of object this tab is: ' + currRecordId.getSObjectType());
		}    
	} else {
		System.debug('SlickSidebarAbstractController - Expecting an id URL paratmer to kick this whole thing off');
	}                     
  } // END of init

  /**
    *
   * This is a workaround to be able to package Person Account fields into an AppExchange Package
   *
   **/
  private boolean isPersonAccountRecord(ID recordId) {
    boolean personAccountsEnabled = false;
    List<Schema.DescribeSObjectResult> describeSObjectResults;
    Map<String, Schema.SObjectField> fieldMap;

    describeSObjectResults = Schema.describeSObjects(new String[] {'Account'});
    fieldMap = describeSObjectResults[0].fields.getMap();

    if ( fieldMap.containsKey('isPersonAccount') ) {
        personAccountsEnabled = true;
    } 

    if (personAccountsEnabled) {
        Account accountRec;
        String query = 'SELECT ID, isPersonAccount FROM Account where Id = ' + '\'' + recordId + '\'';
        accountRec = Database.query(query);
        return Boolean.valueOf(accountRec.get('isPersonAccount'));
    } else {
        return false;
    }
  }  

  /**
   *
   * Pulls the respective contact record using the SlickSidebarControllerContact fieldset
   *
   **/
  private static Contact getContactRecord(ID contactId) {
    return Database.query( 
        SlickSidebarFieldsetHelper.createBaseQueryString(new Contact(), 
          SObjectType.Contact.FieldSets.SlickSidebarControllerContact.getFields(), 
          contactId) 
        );
  }

  /**
   *
   * Pulls the respective contact record using the ContactConsoleWrapper fieldset
   *
   **/
  private static Contact getPersonAccountContactRecord(ID accountId) {
    String queryString;
    queryString = SlickSidebarFieldsetHelper.createBaseQueryString(new Contact(), SObjectType.Contact.FieldSets.SlickSidebarControllerContact.getFields());
    queryString += ' WHERE accountId = \'' + accountId + '\'';
    return Database.query(queryString);
  }  

  /**
   *
   * Pulls the respective account record using the SlickSidebarControllerAccount fieldset
   *
   **/
  private static Account getAccountRecord(ID accountId) {
    return Database.query( 
        SlickSidebarFieldsetHelper.createBaseQueryString(new Account(), 
          SObjectType.Account.FieldSets.SlickSidebarControllerAccount.getFields(), 
          accountId) 
        );
  }

  /**
   *
   * Pulls the respective case record using the SlickSidebarControllerCase fieldset
   *
   **/
  private static Case getCaseRecord(ID caseId) {
    Case theCase;
    try {
      theCase = Database.query( 
        SlickSidebarFieldsetHelper.createBaseQueryString(new Case(), 
          SObjectType.Case.FieldSets.SlickSidebarControllerCase.getFields(), 
          caseId) 
        );
    } catch (Exception ex) {
      theCase = null;
    }
    return theCase;
  }
  /**
   *
   * Pulls the respective lead record using the SlickSidebarControllerLead fieldset
   *
   **/
    //New
  private static Lead getLeadRecord(ID leadId) {
    Lead theLead;
    try {
      theLead = Database.query( 
        SlickSidebarFieldsetHelper.createBaseQueryString(new Lead(), 
          SObjectType.Lead.FieldSets.SlickSidebarControllerLead.getFields(), 
          leadId) 
        );
    } catch (Exception ex) {
      theLead = null;
    }
    return theLead;
  }

  public virtual void UnitTestCompliance() {
    Integer i=0;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;  
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;
    i++;      
  }
}