objects/SlickSidebar__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Accordion_Arrow_Colour__c</fullName>
        <defaultValue>&quot;#009DDC&quot;</defaultValue>
        <inlineHelpText>HEX colour code for the accordion arrows</inlineHelpText>
        <label>Accordion Arrow Colour</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Row_Hover_Colour__c</fullName>
        <defaultValue>&quot;#E0F0FF&quot;</defaultValue>
        <inlineHelpText>HEX colour for mouse hover</inlineHelpText>
        <label>Row Hover Colour</label>
        <length>7</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Show_Activity_History__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Show Activity History</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Customer_Summary__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Show Customer Summary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Generic_Related_List_1__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Show Generic Related List 1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Generic_Related_List_2__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Show Generic Related List 2</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Nearby_Locations__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Show Nearby Locations</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Related_Cases__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Show Related Cases</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Show_Related_Opportunities__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Show Related Opportunities</label>
        <type>Checkbox</type>
    </fields>
    <label>SlickSidebar Configuration</label>
</CustomObject>

classes/SlickSidebarWidgetController.cls
// Copyright 2014, Kevin Akermanis - Sales Engineering, Salesforce.com Inc.
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
// - Redistributions of source code must retain the above copyright notice,
//   this list of conditions and the following disclaimer.
// - Redistributions in binary form must reproduce the above copyright notice,
//   this list of conditions and the following disclaimer in the documentation
//   and/or other materials provided with the distribution.
// - Neither the name of the salesforce.com nor the names of its contributors
//   may be used to endorse or promote products derived from this software
//   without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
// OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

public class SlickSidebarWidgetController{

    public SlickSidebar__c config {
        set;
        get {
            if (config == null) {
                try {
                    config = [SELECT Accordion_Arrow_Colour__c, Show_Customer_Summary__c, Show_Related_Cases__c, Show_Activity_History__c, Show_Nearby_Locations__c,
                      Show_Related_Opportunities__c, Show_Generic_Related_List_1__c, Show_Generic_Related_List_2__c, Row_Hover_Colour__c
                      FROM SlickSidebar__c LIMIT 1];              
                } catch (Exception ex) {
                    config = new SlickSidebar__c();
                    config.name='Default';
                    insert config;
                }                
            }           
            return config;     
        }
    }
    
    public SlickSidebarWidgetController() {
      
    }
}